version: 2

release:
  github:
    owner: package-register
    name: go-utils
  draft: false
  prerelease: false

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  filters:
    exclude: ['.*']

checksum:
  disable: true

signs: []
