version: 2

release:
  github:
    owner: package-register
    name: go-utils
  draft: false
  prerelease: false

snapshot:
  # 移除已弃用的 name_template
  enabled: true

changelog:
  filters:
    exclude: ['.*']

checksum:
  disable: true

builds: [] # 禁用构建步骤，仅发布源码

archives:
  - files:
      - '**/*'

signs: []
