name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        run: |
          git log --pretty=format:"- %s (%h)" > CHANGELOG.md
          echo "# Changelog" > temp_changelog.md
          cat CHANGELOG.md >> temp_changelog.md
          mv temp_changelog.md CHANGELOG.md
          echo "Generated CHANGELOG.md"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          body_path: ./CHANGELOG.md
          files: |
            ./CHANGELOG.md
